### ISSUE TITLE
v2.7.4.0 dosen't trigger alarm. I revert to v2.7.3.0 and it works

### ISSUE THREAD

**Issue by OkOtChA666** [guerrerotook/securitas-direct-new-api#214]
Didn't do much testing. But can confirm after instalation I cannot trigger alarm (no messages or errors)

However, Home assistants displays a message that Securitas Alarm cannot be configured throuhg YAML.

**Comment by edurenye** [comment]
I got the same error after updating to v2.7.4.0.
From the log:
`Log details (ERROR)
Logger: homeassistant.setup
Source: setup.py:280
First occurred: February 28, 2024 at 7:10:19 PM (1 occurrences)
Last logged: February 28, 2024 at 7:10:19 PM

The 'securitas' integration does not support YAML setup, please remove it from your configuration`

**Comment by edurenye** [comment]
@cantupaz 
Here you have the example from the readme file:
```
securitas:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: ES
  check_alarm_panel: false # defaultValue:True | set to false for NOT to check the alarm each time. See features.
```
You need to add this to the configuration.yaml file.
