### ISSUE TITLE
Error loading /config/configuration.yaml: Secret (usuario) not defined

### ISSUE THREAD

**Issue by malguerojorda** [guerrerotook/securitas-direct-new-api#30]
Buenos días, 

Intento configurar el HA, pero me devuelve este error al verificar la configuración. 
No se si tendrá relación en que sea usuario numérico, solamente...

**Comment by guerrerotook** [comment]
¿tienes algún detalle más del error que te da?

**Comment by malguerojorda** [comment]
no mucho más, al validar la configuración, me devuelve este error y no me deja reiniciar.

**Comment by guerrerotook** [comment]
Sigues esta configuration?

```yaml
securitas:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: ES
```
