### ISSUE TITLE
No funciona script "desconectar alarma"

### ISSUE THREAD

**Issue by DJuanillo** [guerrerotook/securitas-direct-new-api#8]
Hola, he configurado dos scripts, uno para conectar y otro para desconectar, el que conecta funciona perfectamente, pero el de desconectarla no funciona, no da error, pero no hace su función, pego el script a ver si veis el error...

Gracias.

`desconectar_alarma:
  alias: Desconectar Alarma
  sequence:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: "mi codigo"
    target:
      entity_id: "mi id"
  mode: single`

**Comment by guerrerotook** [comment]
¿Te funciona desde el panel del HA? Yo no reconozco ese argumento mode. Esto es un ejemplo en mi HA.

```yaml
service: alarm_control_panel.alarm_arm_away
data:
  code: '1234'
target:
  entity_id: alarm_control_panel.123456789
```
